name: cogniplus_mobile
description: Cogniplus mobile app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.11+2
  shared_preferences: ^0.5.8
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  flutter_secure_storage: ^3.3.3
  flutter_svg: ^0.17.4
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  fluttertoast: ^7.0.1+1
  intl: ^0.16.1
  flutter_datetime_picker: ^1.3.8
  smooth_star_rating: ^1.1.1
  flutter_slidable: ^0.5.5
  chewie: ^0.9.10
  font_awesome_flutter: ^8.8.1
  flutter_speed_dial: ^1.2.5
  csv: ^4.0.3
  mailer: ^3.0.4
  flushbar: ^1.10.4
  easy_permission_validator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.5"

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/videos/
    - assets/videos/modulo1/
    - assets/videos/modulo2/
    - assets/videos/modulo3/
    - assets/videos/modulo4/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold_1.ttf
        - asset: fonts/Quicksand-Medium_1.ttf
        - asset: fonts/Quicksand-Light_1.ttf