name: cogniplus_mobile
description: Cogniplus mobile app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.11+2
  shared_preferences: ^0.5.8
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  inview_notifier_list: ^1.0.0
  dio: ^3.0.10
  connectivity: ^2.0.0
  http: ^0.12.2
  flutter_secure_storage: ^3.3.5
  flutter_svg: ^0.19.1
  sqflite: ^1.3.1
  path_provider: ^1.6.11  
  fluttertoast: ^7.1.1
  intl: ^0.16.1
  flutter_datetime_picker: ^1.4.0
  smooth_star_rating: ^1.1.1
  flutter_slidable: ^0.5.5
  chewie: ^0.9.10
  font_awesome_flutter: ^8.8.1
  flutter_speed_dial: ^1.2.5
  csv: ^4.0.3
  mailer: ^3.0.4
  flushbar: ^1.10.4
  easy_permission_validator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icono.png"
  image_path_android: "assets/launcher/icono.png"
  adaptive_icon_background: "assets/launcher/icono.png"
  adaptive_icon_foreground: "assets/launcher/icono.png"

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
        
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold_1.ttf
        - asset: fonts/Quicksand-Medium_1.ttf
        - asset: fonts/Quicksand-Light_1.ttf