name: cogniplus_mobile
description: Cogniplus mobile app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.0.0
  shared_preferences: ^2.0.5
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  inview_notifier_list: ^1.0.0
  connectivity: ^3.0.2
  http: ^0.12.2
  flutter_secure_storage: ^4.0.0
  flutter_svg: ^0.19.3
  path_provider: ^2.0.1
  fluttertoast: ^7.1.8
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.0
  smooth_star_rating: ^1.1.1
  flutter_slidable: ^0.6.0
  chewie: ^1.0.0
  font_awesome_flutter: ^8.11.0
  flutter_speed_dial: ^2.1.1
  csv: ^4.1.0
  url_launcher: ^5.7.10
  mailer: ^4.0.0
  flushbar: ^1.10.4
  easy_permission_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icono.png"
  image_path_android: "assets/launcher/icono.png"
  adaptive_icon_background: "assets/launcher/icono.png"
  adaptive_icon_foreground: "assets/launcher/icono.png"

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/intro.mp4
        
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold_1.ttf
        - asset: fonts/Quicksand-Medium_1.ttf
        - asset: fonts/Quicksand-Light_1.ttf